### ISSUE TITLE
API issue with submit validation API

### ISSUE THREAD

**Issue by codetycon** [gotmoby/moby-api-documentation#1]
Here is my API endpoint:-
$url = "https://staging.gotmoby.com/api/validation/submit/".$vid;

Here is my payload:-
  $postFields = array();
  $filePath1 = "C:\Users\dell\Downloads\A1.jpeg";
  $filePath2 = "C:\Users\dell\Downloads\A2.jpeg";
  $filePath3 = "C:\Users\dell\Downloads\A2.jpeg"; 
  $postFields['front'] = base64_encode(file_get_contents($filePath1));
  $postFields['back'] = base64_encode(file_get_contents($filePath2));
  $postFields['selfie'] = base64_encode(file_get_contents($filePath3));
  $postFields['uniqueId'] = "$UID"; //$UID contans same unique ID sent when creating a validation

Here is my CURL Request 

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://staging.gotmoby.com/api/validation/submit/".$vid,
  CURLOPT_RETURNTRANSFER => true,
  // CURLOPT_ENCODING => "",
  // CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 600,
  // CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "PUT",
  CURLOPT_POSTFIELDS => $postFields,
  CURLOPT_HTTPHEADER => array(
    "Authorization: Bearer {{my token}}",
    'Content-Type: multipart/form-data;',
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

BUT I AM ALWAYS RECEIVING following output
{"front":["The front field is required."],"uniqueId":["The unique id field is required."]}

Can someone please look into this and let me know what is going wrong here..

**Comment by owhite2017** [comment]
Hi there,
 I've looked through your code and it looks like you're using the base64 of the images. Unless you are set up to use PGP encryption then you cannot use base64 images. If you are not using PGP then you will need to upload the file itself rather than the base64 encoded version of it.
I would suggest testing using Postman to get the request correct before you then convert it to code and simply copy it over.

Let me know if you have any further issues.

**Comment by codetycon** [comment]
Actually postman os not converting a correct code for files upload but I
set usePgp to get work with base64.


Is this possible for you to send php code without base64?

Also when I sending request with base64 images in a validation submit api
at once, I received following error

 "An unexpected error occurred please contact Moby to solve your issue.
Error number code: 859177"

Can you please look into this and let me know what is going wrong here.

**Comment by codetycon** [comment]
Finally I find out a solution

Here is a solution 

`
```
<?php      
       $apiHeaders = array();
       $apiHeaders["Authorization"] = "Bearer ".$apiToken['token'];
       $url = "https://staging.gotmoby.com/api/validation/submit/".$validationID;

       $payload = array();
       /*
         Below parameter's represent a full path of file
         $_FILES['front_image']["tmp_name"]
         $_FILES['back_image']["tmp_name"]
         $_FILES['front_image']["selfi_image"]
      */
        $payload['front'] = new CURLFile($_FILES['front_image']["tmp_name"]);
        $payload['back'] = new CURLFile($_FILES['back_image']["tmp_name"]);
        $payload['selfie'] = new CURLFile($_FILES['selfi_image']["tmp_name"]);
        $payload['_method'] = "put";
        $payload['uniqueId'] = $uniqueId;
        $curl = curl_init();

        curl_setopt_array($curl, array(
          // CURLOPT_URL => "http://localhost/web.php",
          CURLOPT_URL => $url,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => "",
          CURLOPT_SAFE_UPLOAD =>false,
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 30,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => "POST",
          CURLOPT_POSTFIELDS => $payload,
          CURLOPT_HTTPHEADER => $apiHeaders,
        ));
        $validationBodyJSON = curl_exec($curl);
        $err = curl_error($curl);
        curl_close($curl);
?>
```
`
